# Generated by Django 3.2.20 on 2023-08-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='computer', max_length=30),
            preserve_default=False,
        ),
    ]
