# Generated by Django 3.2.20 on 2023-08-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_web_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='web_user',
            new_name='webuser',
        ),
    ]
