# Generated by Django 3.2.20 on 2023-08-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_web_user_webuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('discription', models.TextField()),
                ('postimage', models.ImageField(upload_to='postimage')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='email',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='password',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='username',
            field=models.TextField(max_length=30),
        ),
    ]
