# Generated by Django 3.2.20 on 2023-08-16 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20230816_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetime',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webuser',
            name='mobile',
            field=models.TextField(max_length=11),
        ),
    ]
