# Generated by Django 3.2.20 on 2023-08-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20230817_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.TextField(),
        ),
    ]
